### ISSUE TITLE
new user introduction improvements

### ISSUE THREAD

**Issue by hannesdelbeke** [Aodaruma/coa_tools2#33]
**Is your feature request related to a problem? Please describe.**
When arriving on this repo, there is a huge wall of text.
It's not clear on first sight what this addon is about.

**Describe the solution you'd like**
Add images to the README.md to show what the addon looks like and does.
Or even better a GIF

a nice example for a good readme with images https://github.com/FrandSX/sxtools-blender

---

thank you for your hard work reviving this addon 🙏

**Comment by Aodaruma** [comment]
I agree to add images to README.md to make the features more understandable. I'll work on it when I have the time :+1:

**Comment by Aodaruma** [comment]
> I am also glad after almost a 5 year period of waiting for an official update. Thanks for the branch! Also, is it possible to install it on Blender 3.6 and beyond? As of now, I'd like to open a few projects I did back in 2.83, but I'm afraid code will break and corrupt my files. How "retro-compatible" would this addon be? Thank you for your hard work!

Yes! Download zip from master branch and install `/coa_tools2`, and now you can use the addon in Blender 3.6.
I changed UI and operators' name "coa_tools" to "coa_tools2" for preventing to conflict features, but it is recommended to install coa_tools2 without coa_tools and save backup of the project when you load it.
I didn't check that it also works in Blender 4.0. However it will be developed to use in that version!

**Comment by 3dcinetv** [comment]
Great! I'll test it on 3.6 and 4.1 soon. Thanks!

**Comment by Aodaruma** [comment]
I fixed README.md and added screenshots of each exporters with #42

**Comment by hannesdelbeke** [comment]
The new readme looks great 😃
