### ISSUE TITLE
Document how to install Krita plugin

### ISSUE THREAD

**Issue by nonameentername** [Aodaruma/coa_tools2#37]
**Is your feature request related to a problem?**
Add a readme to specify how to install the Krita plugin.

**Describe the solution you'd like**
A simple text description that specifies how to install the plugin.

I was able to install the plugin doing the following:
```
git clone https://github.com/Aodaruma/coa_tools2.git
cd coa_tools2/Krita
zip -r coa_tools2.zip coa_tools2_exporter coa_tools2_exporter.desktop
```
And then from Krita select `Tools -> Scripts -> Import Python Plugin from File`
Select zip file and restart Krita.
Once restarted Krita will have a new Docker with COA Tools Exporter.

To use the plugin select all the layers that should be exported, select export path, export name and press
Export Selected Sprites button.

**Describe alternatives you've considered**
Google search provided the following https://docs.krita.org/en/user_manual/python_scripting/install_custom_python_plugin.html

**Additional context**
Helpful documentation for users.

**Comment by Aodaruma** [comment]
I created PR for add instructions installing Krita plugin into README.md, please check it out!
