### ISSUE TITLE
Can the addon work with Blender 4.3?

### ISSUE THREAD

**Issue by 3dcinetv** [Aodaruma/coa_tools2#53]
Blender 4.3 has been published and I'd like to know if the addon will be compatible in terms of API/GUI with this version.

**Describe the solution you'd like**
I'd like to keep using CoATOOLs branched version in Blender 4.3 please, without any crashes.
Thanks!

**Comment by Aodaruma** [comment]
Thank you for opening the issue. I haven't tried it on 4.3 yet, so I plan to test it myself and work on eliminating the errors (judging from the release notes, there don't seem to be any significant breaking changes).

**Comment by Aodaruma** [comment]
I have fixed several bugs in version 4.3 (or rather, the ones that had been left unattended in the earlier versions, up to 4.2). With this, I believe it should at least run without crashing and function somewhat normally. Could you try testing it a little?
https://github.com/Aodaruma/coa_tools2/tree/upgrade-b3d-4.3-%2353

**Comment by 3dcinetv** [comment]
Thank you so much! I'll test the rigging and drawing tools in this branch, which were mostly causing errors back in 3.1+
I'm using Blender 4.3 now. Yes, I will describe the errors and how to reproduce them.
I can just download the "source code" or are you uploading in the "RELEASES" tab, here on Github?

**Comment by Aodaruma** [comment]
Yes, please download the source code from the ["upgrade-b3d-4.3" branch](https://github.com/Aodaruma/coa_tools2/tree/upgrade-b3d-4.3-%2353) and install the add-on (note that it is not the master branch).

**Comment by Aodaruma** [comment]
I noticed new changes in the original coa_tools, so I merged those fixes into the same branch. If you encounter any errors, please try downloading it again and testing it.

**Comment by 3dcinetv** [comment]
Thank you for the heads up. I saw some commits behind the master branch yesterday, so I am glad you also noticed. Cheers!

**Comment by Aodaruma** [comment]
> Just to clarify, the file coa_tools2-upgrade-b3d-4.3-53.zip is no longer the "new" version, correct?
No, coa_tools2-upgrade-b3d-4.3-53 still reflects the latest changes compared to master. If there are no particular issues, I’m planning to merge these changes into master and release them. Sorry for the confusion.

**Comment by Aodaruma** [comment]
@3dcinetv have there been any errors?
if the version of coa_tools2 seems fine, I’m thinking of merging this into the master branch and closing the issue.

**Comment by 3dcinetv** [comment]
Please allow me one more day, I've been super busy. Thanks!

**Comment by Aodaruma** [comment]
I'll merge the branch into master and create a release. If any issues arise, please open an issue for that :)
